apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: note-taker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: note-taker
  template:  
    metadata: 
      name: note-taker
      labels: 
        app: note-taker
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: note-taker-disk
      containers:
        - name: note-taker
          image: davidsdeveloper/note-taker:v3
          ports: 
            - containerPort: 3001 
          volumeMounts:
            - mountPath: "/mnt/note-taker-db"
              name: volume
          # resources:
          #   limits:
          #     memory: "10G"
          #     cpu: "10G"
